<?xml version="1.0" encoding="utf-8"?><Database Name="WSCAT_DB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=XIYUANER-PC\SQLEXPRESS;Initial Catalog=WSCAT_DB;Persist Security Info=True;User ID=sa" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="WSCAT_DBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.T_City" Member="T_City">
    <Type Name="T_City">
      <Column Name="City_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="City_Code" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="City_Name" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="City_ParentId" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="City_Enable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="City_Clear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_Borrow" Member="T_Borrow">
    <Type Name="T_Borrow">
      <Column Name="Bo_TypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Bo_TypeName" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_Empolyee" Member="T_Empolyee">
    <Type Name="T_Empolyee">
      <Column Name="Emp_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Emp_Code" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_Name" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_zhiwen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Emp_CardCode" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_Depid" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_Sex" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_Card" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_State" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Emp_Phone" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_Bank" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_OpenBank" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Emp_Email" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_Education" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_School" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_Entry" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Emp_safetone" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_safettwo" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Emp_Enable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Emp_Clear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_Department" Member="T_Department">
    <Type Name="T_Department">
      <Column Name="Dt_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Dt_Code" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Dt_RoleCode" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Dt_Name" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Dt_Clear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_BankAccount" Member="T_BankAccount">
    <Type Name="T_BankAccount">
      <Column Name="Ba_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ba_Code" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Ba_OpenBank" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Ba_Account" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Ba_CardHolder" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Ba_Remark" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Ba_AvailablePrice" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Ba_Enable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ba_Clear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_OrderType" Member="T_OrderType">
    <Type Name="T_OrderType">
      <Column Name="Ot_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ot_Name" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_Buy" Member="T_Buy">
    <Type Name="T_Buy">
      <Column Name="Buy_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Buy_Code" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Buy_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Buy_StockCode" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Buy_StockName" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Buy_PurchaseStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Buy_AuditStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Buy_PurchaserID" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Buy_SalesMan" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Buy_Operation" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Buy_AuditMan" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Buy_Remark" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Buy_Satetyone" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Buy_Satetytwo" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Buy_Clear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>