#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WSCAT_DB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertT_City(T_City instance);
    partial void UpdateT_City(T_City instance);
    partial void DeleteT_City(T_City instance);
    partial void InsertT_Borrow(T_Borrow instance);
    partial void UpdateT_Borrow(T_Borrow instance);
    partial void DeleteT_Borrow(T_Borrow instance);
    partial void InsertT_Empolyee(T_Empolyee instance);
    partial void UpdateT_Empolyee(T_Empolyee instance);
    partial void DeleteT_Empolyee(T_Empolyee instance);
    partial void InsertT_Department(T_Department instance);
    partial void UpdateT_Department(T_Department instance);
    partial void DeleteT_Department(T_Department instance);
    partial void InsertT_BankAccount(T_BankAccount instance);
    partial void UpdateT_BankAccount(T_BankAccount instance);
    partial void DeleteT_BankAccount(T_BankAccount instance);
    partial void InsertT_OrderType(T_OrderType instance);
    partial void UpdateT_OrderType(T_OrderType instance);
    partial void DeleteT_OrderType(T_OrderType instance);
    partial void InsertT_Buy(T_Buy instance);
    partial void UpdateT_Buy(T_Buy instance);
    partial void DeleteT_Buy(T_Buy instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DAL.Properties.Settings.Default.WSCAT_DBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_City> T_City
		{
			get
			{
				return this.GetTable<T_City>();
			}
		}
		
		public System.Data.Linq.Table<T_Borrow> T_Borrow
		{
			get
			{
				return this.GetTable<T_Borrow>();
			}
		}
		
		public System.Data.Linq.Table<T_Empolyee> T_Empolyee
		{
			get
			{
				return this.GetTable<T_Empolyee>();
			}
		}
		
		public System.Data.Linq.Table<T_Department> T_Department
		{
			get
			{
				return this.GetTable<T_Department>();
			}
		}
		
		public System.Data.Linq.Table<T_BankAccount> T_BankAccount
		{
			get
			{
				return this.GetTable<T_BankAccount>();
			}
		}
		
		public System.Data.Linq.Table<T_OrderType> T_OrderType
		{
			get
			{
				return this.GetTable<T_OrderType>();
			}
		}
		
		public System.Data.Linq.Table<T_Buy> T_Buy
		{
			get
			{
				return this.GetTable<T_Buy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_City")]
	public partial class T_City : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _City_ID;
		
		private string _City_Code;
		
		private string _City_Name;
		
		private string _City_ParentId;
		
		private System.Nullable<int> _City_Enable;
		
		private System.Nullable<int> _City_Clear;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCity_IDChanging(int value);
    partial void OnCity_IDChanged();
    partial void OnCity_CodeChanging(string value);
    partial void OnCity_CodeChanged();
    partial void OnCity_NameChanging(string value);
    partial void OnCity_NameChanged();
    partial void OnCity_ParentIdChanging(string value);
    partial void OnCity_ParentIdChanged();
    partial void OnCity_EnableChanging(System.Nullable<int> value);
    partial void OnCity_EnableChanged();
    partial void OnCity_ClearChanging(System.Nullable<int> value);
    partial void OnCity_ClearChanged();
    #endregion
		
		public T_City()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int City_ID
		{
			get
			{
				return this._City_ID;
			}
			set
			{
				if ((this._City_ID != value))
				{
					this.OnCity_IDChanging(value);
					this.SendPropertyChanging();
					this._City_ID = value;
					this.SendPropertyChanged("City_ID");
					this.OnCity_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_Code", DbType="NVarChar(512)")]
		public string City_Code
		{
			get
			{
				return this._City_Code;
			}
			set
			{
				if ((this._City_Code != value))
				{
					this.OnCity_CodeChanging(value);
					this.SendPropertyChanging();
					this._City_Code = value;
					this.SendPropertyChanged("City_Code");
					this.OnCity_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_Name", DbType="NVarChar(512)")]
		public string City_Name
		{
			get
			{
				return this._City_Name;
			}
			set
			{
				if ((this._City_Name != value))
				{
					this.OnCity_NameChanging(value);
					this.SendPropertyChanging();
					this._City_Name = value;
					this.SendPropertyChanged("City_Name");
					this.OnCity_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_ParentId", DbType="NVarChar(512)")]
		public string City_ParentId
		{
			get
			{
				return this._City_ParentId;
			}
			set
			{
				if ((this._City_ParentId != value))
				{
					this.OnCity_ParentIdChanging(value);
					this.SendPropertyChanging();
					this._City_ParentId = value;
					this.SendPropertyChanged("City_ParentId");
					this.OnCity_ParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_Enable", DbType="Int")]
		public System.Nullable<int> City_Enable
		{
			get
			{
				return this._City_Enable;
			}
			set
			{
				if ((this._City_Enable != value))
				{
					this.OnCity_EnableChanging(value);
					this.SendPropertyChanging();
					this._City_Enable = value;
					this.SendPropertyChanged("City_Enable");
					this.OnCity_EnableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_Clear", DbType="Int")]
		public System.Nullable<int> City_Clear
		{
			get
			{
				return this._City_Clear;
			}
			set
			{
				if ((this._City_Clear != value))
				{
					this.OnCity_ClearChanging(value);
					this.SendPropertyChanging();
					this._City_Clear = value;
					this.SendPropertyChanged("City_Clear");
					this.OnCity_ClearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Borrow")]
	public partial class T_Borrow : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Bo_TypeID;
		
		private string _Bo_TypeName;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBo_TypeIDChanging(int value);
    partial void OnBo_TypeIDChanged();
    partial void OnBo_TypeNameChanging(string value);
    partial void OnBo_TypeNameChanged();
    #endregion
		
		public T_Borrow()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bo_TypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Bo_TypeID
		{
			get
			{
				return this._Bo_TypeID;
			}
			set
			{
				if ((this._Bo_TypeID != value))
				{
					this.OnBo_TypeIDChanging(value);
					this.SendPropertyChanging();
					this._Bo_TypeID = value;
					this.SendPropertyChanged("Bo_TypeID");
					this.OnBo_TypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bo_TypeName", DbType="NVarChar(512)")]
		public string Bo_TypeName
		{
			get
			{
				return this._Bo_TypeName;
			}
			set
			{
				if ((this._Bo_TypeName != value))
				{
					this.OnBo_TypeNameChanging(value);
					this.SendPropertyChanging();
					this._Bo_TypeName = value;
					this.SendPropertyChanged("Bo_TypeName");
					this.OnBo_TypeNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Empolyee")]
	public partial class T_Empolyee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Emp_ID;
		
		private string _Emp_Code;
		
		private string _Emp_Name;
		
		private string _Emp_zhiwen;
		
		private string _Emp_CardCode;
		
		private string _Emp_Depid;
		
		private string _Emp_Sex;
		
		private string _Emp_Card;
		
		private System.Nullable<int> _Emp_State;
		
		private string _Emp_Phone;
		
		private string _Emp_Bank;
		
		private string _Emp_OpenBank;
		
		private System.Nullable<System.DateTime> _Emp_Birthday;
		
		private string _Emp_Email;
		
		private string _Emp_Education;
		
		private string _Emp_School;
		
		private System.Nullable<System.DateTime> _Emp_Entry;
		
		private string _Emp_safetone;
		
		private string _Emp_safettwo;
		
		private System.Nullable<int> _Emp_Enable;
		
		private System.Nullable<int> _Emp_Clear;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmp_IDChanging(int value);
    partial void OnEmp_IDChanged();
    partial void OnEmp_CodeChanging(string value);
    partial void OnEmp_CodeChanged();
    partial void OnEmp_NameChanging(string value);
    partial void OnEmp_NameChanged();
    partial void OnEmp_zhiwenChanging(string value);
    partial void OnEmp_zhiwenChanged();
    partial void OnEmp_CardCodeChanging(string value);
    partial void OnEmp_CardCodeChanged();
    partial void OnEmp_DepidChanging(string value);
    partial void OnEmp_DepidChanged();
    partial void OnEmp_SexChanging(string value);
    partial void OnEmp_SexChanged();
    partial void OnEmp_CardChanging(string value);
    partial void OnEmp_CardChanged();
    partial void OnEmp_StateChanging(System.Nullable<int> value);
    partial void OnEmp_StateChanged();
    partial void OnEmp_PhoneChanging(string value);
    partial void OnEmp_PhoneChanged();
    partial void OnEmp_BankChanging(string value);
    partial void OnEmp_BankChanged();
    partial void OnEmp_OpenBankChanging(string value);
    partial void OnEmp_OpenBankChanged();
    partial void OnEmp_BirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnEmp_BirthdayChanged();
    partial void OnEmp_EmailChanging(string value);
    partial void OnEmp_EmailChanged();
    partial void OnEmp_EducationChanging(string value);
    partial void OnEmp_EducationChanged();
    partial void OnEmp_SchoolChanging(string value);
    partial void OnEmp_SchoolChanged();
    partial void OnEmp_EntryChanging(System.Nullable<System.DateTime> value);
    partial void OnEmp_EntryChanged();
    partial void OnEmp_safetoneChanging(string value);
    partial void OnEmp_safetoneChanged();
    partial void OnEmp_safettwoChanging(string value);
    partial void OnEmp_safettwoChanged();
    partial void OnEmp_EnableChanging(System.Nullable<int> value);
    partial void OnEmp_EnableChanged();
    partial void OnEmp_ClearChanging(System.Nullable<int> value);
    partial void OnEmp_ClearChanged();
    #endregion
		
		public T_Empolyee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Emp_ID
		{
			get
			{
				return this._Emp_ID;
			}
			set
			{
				if ((this._Emp_ID != value))
				{
					this.OnEmp_IDChanging(value);
					this.SendPropertyChanging();
					this._Emp_ID = value;
					this.SendPropertyChanged("Emp_ID");
					this.OnEmp_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Code", DbType="NVarChar(512)")]
		public string Emp_Code
		{
			get
			{
				return this._Emp_Code;
			}
			set
			{
				if ((this._Emp_Code != value))
				{
					this.OnEmp_CodeChanging(value);
					this.SendPropertyChanging();
					this._Emp_Code = value;
					this.SendPropertyChanged("Emp_Code");
					this.OnEmp_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Name", DbType="NVarChar(512)")]
		public string Emp_Name
		{
			get
			{
				return this._Emp_Name;
			}
			set
			{
				if ((this._Emp_Name != value))
				{
					this.OnEmp_NameChanging(value);
					this.SendPropertyChanging();
					this._Emp_Name = value;
					this.SendPropertyChanged("Emp_Name");
					this.OnEmp_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_zhiwen", DbType="NVarChar(MAX)")]
		public string Emp_zhiwen
		{
			get
			{
				return this._Emp_zhiwen;
			}
			set
			{
				if ((this._Emp_zhiwen != value))
				{
					this.OnEmp_zhiwenChanging(value);
					this.SendPropertyChanging();
					this._Emp_zhiwen = value;
					this.SendPropertyChanged("Emp_zhiwen");
					this.OnEmp_zhiwenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_CardCode", DbType="NVarChar(512)")]
		public string Emp_CardCode
		{
			get
			{
				return this._Emp_CardCode;
			}
			set
			{
				if ((this._Emp_CardCode != value))
				{
					this.OnEmp_CardCodeChanging(value);
					this.SendPropertyChanging();
					this._Emp_CardCode = value;
					this.SendPropertyChanged("Emp_CardCode");
					this.OnEmp_CardCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Depid", DbType="NVarChar(512)")]
		public string Emp_Depid
		{
			get
			{
				return this._Emp_Depid;
			}
			set
			{
				if ((this._Emp_Depid != value))
				{
					this.OnEmp_DepidChanging(value);
					this.SendPropertyChanging();
					this._Emp_Depid = value;
					this.SendPropertyChanged("Emp_Depid");
					this.OnEmp_DepidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Sex", DbType="NVarChar(512)")]
		public string Emp_Sex
		{
			get
			{
				return this._Emp_Sex;
			}
			set
			{
				if ((this._Emp_Sex != value))
				{
					this.OnEmp_SexChanging(value);
					this.SendPropertyChanging();
					this._Emp_Sex = value;
					this.SendPropertyChanged("Emp_Sex");
					this.OnEmp_SexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Card", DbType="NVarChar(512)")]
		public string Emp_Card
		{
			get
			{
				return this._Emp_Card;
			}
			set
			{
				if ((this._Emp_Card != value))
				{
					this.OnEmp_CardChanging(value);
					this.SendPropertyChanging();
					this._Emp_Card = value;
					this.SendPropertyChanged("Emp_Card");
					this.OnEmp_CardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_State", DbType="Int")]
		public System.Nullable<int> Emp_State
		{
			get
			{
				return this._Emp_State;
			}
			set
			{
				if ((this._Emp_State != value))
				{
					this.OnEmp_StateChanging(value);
					this.SendPropertyChanging();
					this._Emp_State = value;
					this.SendPropertyChanged("Emp_State");
					this.OnEmp_StateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Phone", DbType="NVarChar(512)")]
		public string Emp_Phone
		{
			get
			{
				return this._Emp_Phone;
			}
			set
			{
				if ((this._Emp_Phone != value))
				{
					this.OnEmp_PhoneChanging(value);
					this.SendPropertyChanging();
					this._Emp_Phone = value;
					this.SendPropertyChanged("Emp_Phone");
					this.OnEmp_PhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Bank", DbType="NVarChar(512)")]
		public string Emp_Bank
		{
			get
			{
				return this._Emp_Bank;
			}
			set
			{
				if ((this._Emp_Bank != value))
				{
					this.OnEmp_BankChanging(value);
					this.SendPropertyChanging();
					this._Emp_Bank = value;
					this.SendPropertyChanged("Emp_Bank");
					this.OnEmp_BankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_OpenBank", DbType="NVarChar(512)")]
		public string Emp_OpenBank
		{
			get
			{
				return this._Emp_OpenBank;
			}
			set
			{
				if ((this._Emp_OpenBank != value))
				{
					this.OnEmp_OpenBankChanging(value);
					this.SendPropertyChanging();
					this._Emp_OpenBank = value;
					this.SendPropertyChanged("Emp_OpenBank");
					this.OnEmp_OpenBankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> Emp_Birthday
		{
			get
			{
				return this._Emp_Birthday;
			}
			set
			{
				if ((this._Emp_Birthday != value))
				{
					this.OnEmp_BirthdayChanging(value);
					this.SendPropertyChanging();
					this._Emp_Birthday = value;
					this.SendPropertyChanged("Emp_Birthday");
					this.OnEmp_BirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Email", DbType="NVarChar(512)")]
		public string Emp_Email
		{
			get
			{
				return this._Emp_Email;
			}
			set
			{
				if ((this._Emp_Email != value))
				{
					this.OnEmp_EmailChanging(value);
					this.SendPropertyChanging();
					this._Emp_Email = value;
					this.SendPropertyChanged("Emp_Email");
					this.OnEmp_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Education", DbType="NVarChar(512)")]
		public string Emp_Education
		{
			get
			{
				return this._Emp_Education;
			}
			set
			{
				if ((this._Emp_Education != value))
				{
					this.OnEmp_EducationChanging(value);
					this.SendPropertyChanging();
					this._Emp_Education = value;
					this.SendPropertyChanged("Emp_Education");
					this.OnEmp_EducationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_School", DbType="NVarChar(512)")]
		public string Emp_School
		{
			get
			{
				return this._Emp_School;
			}
			set
			{
				if ((this._Emp_School != value))
				{
					this.OnEmp_SchoolChanging(value);
					this.SendPropertyChanging();
					this._Emp_School = value;
					this.SendPropertyChanged("Emp_School");
					this.OnEmp_SchoolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Entry", DbType="DateTime")]
		public System.Nullable<System.DateTime> Emp_Entry
		{
			get
			{
				return this._Emp_Entry;
			}
			set
			{
				if ((this._Emp_Entry != value))
				{
					this.OnEmp_EntryChanging(value);
					this.SendPropertyChanging();
					this._Emp_Entry = value;
					this.SendPropertyChanged("Emp_Entry");
					this.OnEmp_EntryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_safetone", DbType="NVarChar(512)")]
		public string Emp_safetone
		{
			get
			{
				return this._Emp_safetone;
			}
			set
			{
				if ((this._Emp_safetone != value))
				{
					this.OnEmp_safetoneChanging(value);
					this.SendPropertyChanging();
					this._Emp_safetone = value;
					this.SendPropertyChanged("Emp_safetone");
					this.OnEmp_safetoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_safettwo", DbType="NVarChar(512)")]
		public string Emp_safettwo
		{
			get
			{
				return this._Emp_safettwo;
			}
			set
			{
				if ((this._Emp_safettwo != value))
				{
					this.OnEmp_safettwoChanging(value);
					this.SendPropertyChanging();
					this._Emp_safettwo = value;
					this.SendPropertyChanged("Emp_safettwo");
					this.OnEmp_safettwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Enable", DbType="Int")]
		public System.Nullable<int> Emp_Enable
		{
			get
			{
				return this._Emp_Enable;
			}
			set
			{
				if ((this._Emp_Enable != value))
				{
					this.OnEmp_EnableChanging(value);
					this.SendPropertyChanging();
					this._Emp_Enable = value;
					this.SendPropertyChanged("Emp_Enable");
					this.OnEmp_EnableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Clear", DbType="Int")]
		public System.Nullable<int> Emp_Clear
		{
			get
			{
				return this._Emp_Clear;
			}
			set
			{
				if ((this._Emp_Clear != value))
				{
					this.OnEmp_ClearChanging(value);
					this.SendPropertyChanging();
					this._Emp_Clear = value;
					this.SendPropertyChanged("Emp_Clear");
					this.OnEmp_ClearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Department")]
	public partial class T_Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Dt_ID;
		
		private string _Dt_Code;
		
		private string _Dt_RoleCode;
		
		private string _Dt_Name;
		
		private System.Nullable<int> _Dt_Clear;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDt_IDChanging(int value);
    partial void OnDt_IDChanged();
    partial void OnDt_CodeChanging(string value);
    partial void OnDt_CodeChanged();
    partial void OnDt_RoleCodeChanging(string value);
    partial void OnDt_RoleCodeChanged();
    partial void OnDt_NameChanging(string value);
    partial void OnDt_NameChanged();
    partial void OnDt_ClearChanging(System.Nullable<int> value);
    partial void OnDt_ClearChanged();
    #endregion
		
		public T_Department()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dt_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Dt_ID
		{
			get
			{
				return this._Dt_ID;
			}
			set
			{
				if ((this._Dt_ID != value))
				{
					this.OnDt_IDChanging(value);
					this.SendPropertyChanging();
					this._Dt_ID = value;
					this.SendPropertyChanged("Dt_ID");
					this.OnDt_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dt_Code", DbType="NVarChar(512)")]
		public string Dt_Code
		{
			get
			{
				return this._Dt_Code;
			}
			set
			{
				if ((this._Dt_Code != value))
				{
					this.OnDt_CodeChanging(value);
					this.SendPropertyChanging();
					this._Dt_Code = value;
					this.SendPropertyChanged("Dt_Code");
					this.OnDt_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dt_RoleCode", DbType="NVarChar(512)")]
		public string Dt_RoleCode
		{
			get
			{
				return this._Dt_RoleCode;
			}
			set
			{
				if ((this._Dt_RoleCode != value))
				{
					this.OnDt_RoleCodeChanging(value);
					this.SendPropertyChanging();
					this._Dt_RoleCode = value;
					this.SendPropertyChanged("Dt_RoleCode");
					this.OnDt_RoleCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dt_Name", DbType="NVarChar(512)")]
		public string Dt_Name
		{
			get
			{
				return this._Dt_Name;
			}
			set
			{
				if ((this._Dt_Name != value))
				{
					this.OnDt_NameChanging(value);
					this.SendPropertyChanging();
					this._Dt_Name = value;
					this.SendPropertyChanged("Dt_Name");
					this.OnDt_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dt_Clear", DbType="Int")]
		public System.Nullable<int> Dt_Clear
		{
			get
			{
				return this._Dt_Clear;
			}
			set
			{
				if ((this._Dt_Clear != value))
				{
					this.OnDt_ClearChanging(value);
					this.SendPropertyChanging();
					this._Dt_Clear = value;
					this.SendPropertyChanged("Dt_Clear");
					this.OnDt_ClearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_BankAccount")]
	public partial class T_BankAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ba_ID;
		
		private string _Ba_Code;
		
		private string _Ba_OpenBank;
		
		private string _Ba_Account;
		
		private string _Ba_CardHolder;
		
		private string _Ba_Remark;
		
		private string _Ba_AvailablePrice;
		
		private System.Nullable<int> _Ba_Enable;
		
		private System.Nullable<int> _Ba_Clear;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBa_IDChanging(int value);
    partial void OnBa_IDChanged();
    partial void OnBa_CodeChanging(string value);
    partial void OnBa_CodeChanged();
    partial void OnBa_OpenBankChanging(string value);
    partial void OnBa_OpenBankChanged();
    partial void OnBa_AccountChanging(string value);
    partial void OnBa_AccountChanged();
    partial void OnBa_CardHolderChanging(string value);
    partial void OnBa_CardHolderChanged();
    partial void OnBa_RemarkChanging(string value);
    partial void OnBa_RemarkChanged();
    partial void OnBa_AvailablePriceChanging(string value);
    partial void OnBa_AvailablePriceChanged();
    partial void OnBa_EnableChanging(System.Nullable<int> value);
    partial void OnBa_EnableChanged();
    partial void OnBa_ClearChanging(System.Nullable<int> value);
    partial void OnBa_ClearChanged();
    #endregion
		
		public T_BankAccount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ba_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ba_ID
		{
			get
			{
				return this._Ba_ID;
			}
			set
			{
				if ((this._Ba_ID != value))
				{
					this.OnBa_IDChanging(value);
					this.SendPropertyChanging();
					this._Ba_ID = value;
					this.SendPropertyChanged("Ba_ID");
					this.OnBa_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ba_Code", DbType="NVarChar(512)")]
		public string Ba_Code
		{
			get
			{
				return this._Ba_Code;
			}
			set
			{
				if ((this._Ba_Code != value))
				{
					this.OnBa_CodeChanging(value);
					this.SendPropertyChanging();
					this._Ba_Code = value;
					this.SendPropertyChanged("Ba_Code");
					this.OnBa_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ba_OpenBank", DbType="NVarChar(512)")]
		public string Ba_OpenBank
		{
			get
			{
				return this._Ba_OpenBank;
			}
			set
			{
				if ((this._Ba_OpenBank != value))
				{
					this.OnBa_OpenBankChanging(value);
					this.SendPropertyChanging();
					this._Ba_OpenBank = value;
					this.SendPropertyChanged("Ba_OpenBank");
					this.OnBa_OpenBankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ba_Account", DbType="NVarChar(512)")]
		public string Ba_Account
		{
			get
			{
				return this._Ba_Account;
			}
			set
			{
				if ((this._Ba_Account != value))
				{
					this.OnBa_AccountChanging(value);
					this.SendPropertyChanging();
					this._Ba_Account = value;
					this.SendPropertyChanged("Ba_Account");
					this.OnBa_AccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ba_CardHolder", DbType="NVarChar(512)")]
		public string Ba_CardHolder
		{
			get
			{
				return this._Ba_CardHolder;
			}
			set
			{
				if ((this._Ba_CardHolder != value))
				{
					this.OnBa_CardHolderChanging(value);
					this.SendPropertyChanging();
					this._Ba_CardHolder = value;
					this.SendPropertyChanged("Ba_CardHolder");
					this.OnBa_CardHolderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ba_Remark", DbType="NVarChar(1024)")]
		public string Ba_Remark
		{
			get
			{
				return this._Ba_Remark;
			}
			set
			{
				if ((this._Ba_Remark != value))
				{
					this.OnBa_RemarkChanging(value);
					this.SendPropertyChanging();
					this._Ba_Remark = value;
					this.SendPropertyChanged("Ba_Remark");
					this.OnBa_RemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ba_AvailablePrice", DbType="NVarChar(512)")]
		public string Ba_AvailablePrice
		{
			get
			{
				return this._Ba_AvailablePrice;
			}
			set
			{
				if ((this._Ba_AvailablePrice != value))
				{
					this.OnBa_AvailablePriceChanging(value);
					this.SendPropertyChanging();
					this._Ba_AvailablePrice = value;
					this.SendPropertyChanged("Ba_AvailablePrice");
					this.OnBa_AvailablePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ba_Enable", DbType="Int")]
		public System.Nullable<int> Ba_Enable
		{
			get
			{
				return this._Ba_Enable;
			}
			set
			{
				if ((this._Ba_Enable != value))
				{
					this.OnBa_EnableChanging(value);
					this.SendPropertyChanging();
					this._Ba_Enable = value;
					this.SendPropertyChanged("Ba_Enable");
					this.OnBa_EnableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ba_Clear", DbType="Int")]
		public System.Nullable<int> Ba_Clear
		{
			get
			{
				return this._Ba_Clear;
			}
			set
			{
				if ((this._Ba_Clear != value))
				{
					this.OnBa_ClearChanging(value);
					this.SendPropertyChanging();
					this._Ba_Clear = value;
					this.SendPropertyChanged("Ba_Clear");
					this.OnBa_ClearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_OrderType")]
	public partial class T_OrderType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ot_ID;
		
		private string _Ot_Name;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOt_IDChanging(int value);
    partial void OnOt_IDChanged();
    partial void OnOt_NameChanging(string value);
    partial void OnOt_NameChanged();
    #endregion
		
		public T_OrderType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ot_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ot_ID
		{
			get
			{
				return this._Ot_ID;
			}
			set
			{
				if ((this._Ot_ID != value))
				{
					this.OnOt_IDChanging(value);
					this.SendPropertyChanging();
					this._Ot_ID = value;
					this.SendPropertyChanged("Ot_ID");
					this.OnOt_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ot_Name", DbType="NVarChar(512)")]
		public string Ot_Name
		{
			get
			{
				return this._Ot_Name;
			}
			set
			{
				if ((this._Ot_Name != value))
				{
					this.OnOt_NameChanging(value);
					this.SendPropertyChanging();
					this._Ot_Name = value;
					this.SendPropertyChanged("Ot_Name");
					this.OnOt_NameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Buy")]
	public partial class T_Buy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Buy_ID;
		
		private string _Buy_Code;
		
		private System.Nullable<System.DateTime> _Buy_Date;
		
		private string _Buy_StockCode;
		
		private string _Buy_StockName;
		
		private System.Nullable<int> _Buy_PurchaseStatus;
		
		private System.Nullable<int> _Buy_AuditStatus;
		
		private string _Buy_PurchaserID;
		
		private string _Buy_SalesMan;
		
		private string _Buy_Operation;
		
		private string _Buy_AuditMan;
		
		private string _Buy_Remark;
		
		private string _Buy_Satetyone;
		
		private string _Buy_Satetytwo;
		
		private System.Nullable<int> _Buy_Clear;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBuy_IDChanging(int value);
    partial void OnBuy_IDChanged();
    partial void OnBuy_CodeChanging(string value);
    partial void OnBuy_CodeChanged();
    partial void OnBuy_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnBuy_DateChanged();
    partial void OnBuy_StockCodeChanging(string value);
    partial void OnBuy_StockCodeChanged();
    partial void OnBuy_StockNameChanging(string value);
    partial void OnBuy_StockNameChanged();
    partial void OnBuy_PurchaseStatusChanging(System.Nullable<int> value);
    partial void OnBuy_PurchaseStatusChanged();
    partial void OnBuy_AuditStatusChanging(System.Nullable<int> value);
    partial void OnBuy_AuditStatusChanged();
    partial void OnBuy_PurchaserIDChanging(string value);
    partial void OnBuy_PurchaserIDChanged();
    partial void OnBuy_SalesManChanging(string value);
    partial void OnBuy_SalesManChanged();
    partial void OnBuy_OperationChanging(string value);
    partial void OnBuy_OperationChanged();
    partial void OnBuy_AuditManChanging(string value);
    partial void OnBuy_AuditManChanged();
    partial void OnBuy_RemarkChanging(string value);
    partial void OnBuy_RemarkChanged();
    partial void OnBuy_SatetyoneChanging(string value);
    partial void OnBuy_SatetyoneChanged();
    partial void OnBuy_SatetytwoChanging(string value);
    partial void OnBuy_SatetytwoChanged();
    partial void OnBuy_ClearChanging(System.Nullable<int> value);
    partial void OnBuy_ClearChanged();
    #endregion
		
		public T_Buy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Buy_ID
		{
			get
			{
				return this._Buy_ID;
			}
			set
			{
				if ((this._Buy_ID != value))
				{
					this.OnBuy_IDChanging(value);
					this.SendPropertyChanging();
					this._Buy_ID = value;
					this.SendPropertyChanged("Buy_ID");
					this.OnBuy_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_Code", DbType="NVarChar(512)")]
		public string Buy_Code
		{
			get
			{
				return this._Buy_Code;
			}
			set
			{
				if ((this._Buy_Code != value))
				{
					this.OnBuy_CodeChanging(value);
					this.SendPropertyChanging();
					this._Buy_Code = value;
					this.SendPropertyChanged("Buy_Code");
					this.OnBuy_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Buy_Date
		{
			get
			{
				return this._Buy_Date;
			}
			set
			{
				if ((this._Buy_Date != value))
				{
					this.OnBuy_DateChanging(value);
					this.SendPropertyChanging();
					this._Buy_Date = value;
					this.SendPropertyChanged("Buy_Date");
					this.OnBuy_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_StockCode", DbType="NVarChar(512)")]
		public string Buy_StockCode
		{
			get
			{
				return this._Buy_StockCode;
			}
			set
			{
				if ((this._Buy_StockCode != value))
				{
					this.OnBuy_StockCodeChanging(value);
					this.SendPropertyChanging();
					this._Buy_StockCode = value;
					this.SendPropertyChanged("Buy_StockCode");
					this.OnBuy_StockCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_StockName", DbType="NVarChar(512)")]
		public string Buy_StockName
		{
			get
			{
				return this._Buy_StockName;
			}
			set
			{
				if ((this._Buy_StockName != value))
				{
					this.OnBuy_StockNameChanging(value);
					this.SendPropertyChanging();
					this._Buy_StockName = value;
					this.SendPropertyChanged("Buy_StockName");
					this.OnBuy_StockNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_PurchaseStatus", DbType="Int")]
		public System.Nullable<int> Buy_PurchaseStatus
		{
			get
			{
				return this._Buy_PurchaseStatus;
			}
			set
			{
				if ((this._Buy_PurchaseStatus != value))
				{
					this.OnBuy_PurchaseStatusChanging(value);
					this.SendPropertyChanging();
					this._Buy_PurchaseStatus = value;
					this.SendPropertyChanged("Buy_PurchaseStatus");
					this.OnBuy_PurchaseStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_AuditStatus", DbType="Int")]
		public System.Nullable<int> Buy_AuditStatus
		{
			get
			{
				return this._Buy_AuditStatus;
			}
			set
			{
				if ((this._Buy_AuditStatus != value))
				{
					this.OnBuy_AuditStatusChanging(value);
					this.SendPropertyChanging();
					this._Buy_AuditStatus = value;
					this.SendPropertyChanged("Buy_AuditStatus");
					this.OnBuy_AuditStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_PurchaserID", DbType="NVarChar(512)")]
		public string Buy_PurchaserID
		{
			get
			{
				return this._Buy_PurchaserID;
			}
			set
			{
				if ((this._Buy_PurchaserID != value))
				{
					this.OnBuy_PurchaserIDChanging(value);
					this.SendPropertyChanging();
					this._Buy_PurchaserID = value;
					this.SendPropertyChanged("Buy_PurchaserID");
					this.OnBuy_PurchaserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_SalesMan", DbType="NVarChar(512)")]
		public string Buy_SalesMan
		{
			get
			{
				return this._Buy_SalesMan;
			}
			set
			{
				if ((this._Buy_SalesMan != value))
				{
					this.OnBuy_SalesManChanging(value);
					this.SendPropertyChanging();
					this._Buy_SalesMan = value;
					this.SendPropertyChanged("Buy_SalesMan");
					this.OnBuy_SalesManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_Operation", DbType="NVarChar(512)")]
		public string Buy_Operation
		{
			get
			{
				return this._Buy_Operation;
			}
			set
			{
				if ((this._Buy_Operation != value))
				{
					this.OnBuy_OperationChanging(value);
					this.SendPropertyChanging();
					this._Buy_Operation = value;
					this.SendPropertyChanged("Buy_Operation");
					this.OnBuy_OperationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_AuditMan", DbType="NVarChar(512)")]
		public string Buy_AuditMan
		{
			get
			{
				return this._Buy_AuditMan;
			}
			set
			{
				if ((this._Buy_AuditMan != value))
				{
					this.OnBuy_AuditManChanging(value);
					this.SendPropertyChanging();
					this._Buy_AuditMan = value;
					this.SendPropertyChanged("Buy_AuditMan");
					this.OnBuy_AuditManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_Remark", DbType="NVarChar(1024)")]
		public string Buy_Remark
		{
			get
			{
				return this._Buy_Remark;
			}
			set
			{
				if ((this._Buy_Remark != value))
				{
					this.OnBuy_RemarkChanging(value);
					this.SendPropertyChanging();
					this._Buy_Remark = value;
					this.SendPropertyChanged("Buy_Remark");
					this.OnBuy_RemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_Satetyone", DbType="NVarChar(512)")]
		public string Buy_Satetyone
		{
			get
			{
				return this._Buy_Satetyone;
			}
			set
			{
				if ((this._Buy_Satetyone != value))
				{
					this.OnBuy_SatetyoneChanging(value);
					this.SendPropertyChanging();
					this._Buy_Satetyone = value;
					this.SendPropertyChanged("Buy_Satetyone");
					this.OnBuy_SatetyoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_Satetytwo", DbType="NVarChar(512)")]
		public string Buy_Satetytwo
		{
			get
			{
				return this._Buy_Satetytwo;
			}
			set
			{
				if ((this._Buy_Satetytwo != value))
				{
					this.OnBuy_SatetytwoChanging(value);
					this.SendPropertyChanging();
					this._Buy_Satetytwo = value;
					this.SendPropertyChanged("Buy_Satetytwo");
					this.OnBuy_SatetytwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_Clear", DbType="Int")]
		public System.Nullable<int> Buy_Clear
		{
			get
			{
				return this._Buy_Clear;
			}
			set
			{
				if ((this._Buy_Clear != value))
				{
					this.OnBuy_ClearChanging(value);
					this.SendPropertyChanging();
					this._Buy_Clear = value;
					this.SendPropertyChanged("Buy_Clear");
					this.OnBuy_ClearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
